# Generated by Django 5.1.4 on 2024-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgroupdevices',
            options={'verbose_name': 'Группа устройств', 'verbose_name_plural': 'Группы устройств'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AddField(
            model_name='accessgroupdevices',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='device_groups', to='devices.device'),
        ),
        migrations.DeleteModel(
            name='AccessGroupDevicesMap',
        ),
    ]
