# Generated by Django 5.1.4 on 2024-12-19 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('rfid', 'RFID'), ('mobile_id', 'Mobile ID'), ('qr', 'QR Code'), ('barcode', 'Barcode')], max_length=50)),
                ('credential_value', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.user')),
            ],
        ),
    ]
