# Generated by Django 5.1.4 on 2024-12-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'verbose_name': 'Идентификатор', 'verbose_name_plural': 'Идентификаторы'},
        ),
    ]
