# Generated by Django 5.1.4 on 2024-12-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_accessgroupdevices_remove_user_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='password_hash',
        ),
    ]
