# Generated by Django 5.1.4 on 2024-12-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запись журнала', 'verbose_name_plural': 'Журнал проходов'},
        ),
    ]
